backend: "traccc"
max_batch_size: 0
input [
   {
    name: "GEOMETRY_ID"
    data_type: TYPE_UINT64
    dims: [ -1 ]
  },
  {
    name: "FEATURES"
    data_type: TYPE_FP64
    dims: [ -1, 7 ]
  }
]
output [
  {
    name: "chi2"
    data_type: TYPE_FP32
    dims: [-1]
  },
  {
    name: "ndf"
    data_type: TYPE_FP32
    dims: [-1]
  },
  {
    name: "local_positions"
    data_type: TYPE_FP32
    dims: [-1, 2]
  },
  {
    name: "variances"
    data_type: TYPE_FP32
    dims: [-1, 2]
  },
  {
    name: "detray_ids"
    data_type: TYPE_UINT64
    dims: [-1]
  },
  {
    name: "measurement_ids"
    data_type: TYPE_UINT64
    dims: [-1]
  },
  {
    name: "measurement_dims"
    data_type: TYPE_UINT32
    dims: [-1]
  },
  {
    name: "times"
    data_type: TYPE_FP32
    dims: [-1]
  }
]
instance_group [
  {
    count: 1
    kind: KIND_GPU
    gpus: [0]
  }
]

parameters: {
  key: "EXECUTION_MODEL_PATH",
  value: {string_value: "/global/cfs/projectdirs/m3443/data/ACTS-aaS/models/smeared_hits/"}
}